#!/usr/bin/env python3
import os
import sys
import subprocess
import venv
import json

# File Name Settings
FILE_NAME_REQ = "requirements.txt"
FILE_NAME_VENV = "venv"
FILE_NAME_ENV = ".env"

# App settings
APP_SOURCES_NAME = "src"
APP_MAIN_NAME = "app"
APP_PATHS = ["src", "test"]

def load_env(project_root):
    env_path = os.path.join(project_root, FILE_NAME_ENV)
    if not os.path.exists(env_path): return

    with open(env_path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, value = line.split("=", 1)
                os.environ[key.strip()] = value.strip().strip("'").strip('"')

def install_requirements(project_root):
    requirements_file = os.path.join(project_root, FILE_NAME_REQ)
    venv_dir = os.path.join(project_root, FILE_NAME_VENV)

    if not os.path.exists(requirements_file):
        print(f"--- Please make sure {FILE_NAME_REQ} file is present")
        return

    if os.name == "nt":
        pip_exe = os.path.join(venv_dir, "Scripts", "pip.exe")
    else:
        pip_exe = os.path.join(venv_dir, "bin", "pip")
    subprocess.check_call([pip_exe, "install", "-r", requirements_file])

def run_python(project_root, app_name, args):
    venv_dir = os.path.join(project_root, FILE_NAME_VENV)
    python_exe = os.path.join(venv_dir, "bin", "python") if os.name != "nt" else os.path.join(venv_dir, "Scripts", "python.exe")
    subprocess.run([python_exe, '-m', app_name] + args)

def get_python_path(project_root):
    sep = os.pathsep
    src_dir = os.path.join(project_root, APP_SOURCES_NAME)
    return f"{project_root}{sep}{src_dir}"

def main():
    # Setup paths
    project_root = os.path.abspath(os.path.dirname(__file__))
    venv_dir = os.path.join(project_root, FILE_NAME_VENV)
    requirements_file = os.path.join(project_root, FILE_NAME_REQ)

    # Set PYTHONPATH to the project root
    python_path = get_python_path(project_root)
    os.environ["PYTHONPATH"] = python_path
    load_env(project_root)

    # Handle Virtual Environment
    if not os.path.exists(venv_dir):
        print(f"--- Creating virtual environment in {venv_dir} ...")
        venv.create(venv_dir, with_pip=True)
        
        # Install requirements if they exist
        if os.path.exists(requirements_file):
            print("--- Installing requirements.txt ...")
            install_requirements(project_root)

    # Run python
    args = sys.argv[1:]
    run_python(project_root, APP_MAIN_NAME, args)

if __name__ == "__main__":
    main()